export const CART_FETCH_REQUEST = "CART_FETCH_REQUEST";
export const CART_FETCH_SUCCESS = "CART_FETCH_SUCCESS";
export const CART_FETCH_FAILURE = "CART_FETCH_FAILURE";

export const CART_CREATION_REQUEST = "CART_CREATION_REQUEST";
export const CART_CREATION_SUCCESS = "CART_CREATION_SUCCESS";
export const CART_CREATION_FAILURE = "CART_CREATION_FAILURE";

export const CART_UPDATE_REQUEST = "CART_UPDATE_REQUEST";
export const CART_UPDATE_SUCCESS = "CART_UPDATE_SUCCESS";
export const CART_UPDATE_FAILURE = "CART_UPDATE_FAILURE";

export const CART_DELETE_REQUEST = "CART_DELETE_REQUEST";
export const CART_DELETE_SUCCESS = "CART_DELETE_SUCCESS";
export const CART_DELETE_FAILURE = "CART_DELETE_FAILURE";


export const INCREASE_ITEM_QTY = 'INCREASE_ITEM_QTY';
export const DECREASE_ITEM_QTY = 'DECREASE_ITEM_QTY';
export const APPLY_COUPON = 'APPLY_COUPON';