export const PRODUCT_FETCH_REQUEST =  "PRODUCT_FETCH_REQUEST"
export const PRODUCT_FETCH_SUCCESS =  "PRODUCT_FETCH_SUCCESS"
export const PRODUCT_FETCH_FAILURE =  "PRODUCT_FETCH_FAILURE"

export const PRODUCT_SINGLE_FETCH_REQUEST =  "PRODUCT_SINGLE_FETCH_REQUEST"
export const PRODUCT_SINGLE_FETCH_SUCCESS =  "PRODUCT_SINGLE_FETCH_SUCCESS"
export const PRODUCT_SINGLE_FETCH_FAILURE =  "PRODUCT_SINGLE_FETCH_FAILURE"

export const PRODUCT_CREATION_REQUEST = "PRODUCT_CREATION_REQUEST";
export const PRODUCT_CREATION_SUCCESS = "PRODUCT_CREATION_SUCCESS";
export const PRODUCT_CREATION_FAILURE = "PRODUCT_CREATION_FAILURE";

export const PRODUCT_UPDATE_REQUEST = "PRODUCT_UPDATE_REQUEST";
export const PRODUCT_UPDATE_SUCCESS = "PRODUCT_UPDATE_SUCCESS";
export const PRODUCT_UPDATE_FAILURE = "PRODUCT_UPDATE_FAILURE";

export const PRODUCT_DELETE_REQUEST = "PRODUCT_DELETE_REQUEST";
export const PRODUCT_DELETE_SUCCESS = "PRODUCT_DELETE_SUCCESS";
export const PRODUCT_DELETE_FAILURE = "PRODUCT_DELETE_FAILURE";


